# Generated by Django 2.0 on 2017-08-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(default='image', max_length=32)),
                ('desc', models.TextField(default='image desc')),
                ('file', models.ImageField(upload_to='')),
            ],
        ),
    ]
