# Generated by Django 2.0 on 2017-08-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filePath',
            field=models.CharField(default='asdadsa', max_length=150),
            preserve_default=False,
        ),
    ]
