# Generated by Django 2.0 on 2017-08-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_image_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
    ]
