# Generated by Django 2.0 on 2017-08-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_auto_20170829_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='fileName',
            field=models.CharField(default='12', max_length=32),
            preserve_default=False,
        ),
    ]
